oathkeeper:
  config:
    serve:
      proxy:
        port: 6003 # run the proxy at port 4455

    errors:
      fallback:
        - json
      handlers:
        json:
          enabled: true
          config:
            verbose: true
        redirect:
          enabled: true
          config:
            to: https://www.ory.sh/docs


    authorizers:
      remote_json:
        enabled: true
        config:
          remote: http://192.168.1.15:6002/api/decide/MakeDecision
          payload: |
            {
              "resource": {
                "type":"http",
                "id":"{{ printIndex .MatchContext.RegexpCaptureGroups 0 }}"
                },
              "action":{
                "name":"{{ .MatchContext.Method}}"
              }
            }

    authenticators:
      noop:
        enabled: true

    mutators:
      noop:
        enabled: true