replicaCount: 1

user: ""

image:
  repository: registry
  tag: latest
  pullPolicy: Never

service:
  name: registry
  type: ClusterIP
  port: 6004
  targetPort: 5000

env:
  environment: Production
  httpPorts: 5000

volume:
  appsettingsConfigMapName: registry-appsettings
  keysSecretName: registry-keys
