services:
  auth:
    image: oryd/hydra:v2.2.0
    ports:
      - "6001:4444" # Public port
      - "6000:4445" # Admin port
    command: serve -c /etc/config/hydra/hydra.yml all --dev
    volumes:
      - type: bind
        source: ./config/hydra
        target: /etc/config/hydra
    environment:
      - DSN=memory
    restart: unless-stopped
    networks:
      - iam4cc
  pep:
    image: oryd/oathkeeper:v0.40.7
    ports:
      - "6003:6003" # Proxy
    command: serve --config=/etc/config/oathkeeper/config.yaml
    volumes:
      - type: bind
        source: ./config/oathkeeper
        target: /etc/config/oathkeeper
    restart: on-failure
    networks:
      - iam4cc
  pdp:
    image: pdp
    ports:
      - "6002:6002"
    environment:
      - ASPNETCORE_HTTP_PORTS=6002
    restart: on-failure
    networks:
      - iam4cc
 
  registry:
    image: registry
    ports:
      - "6004:6004"
    environment:
      - ASPNETCORE_HTTP_PORTS=6004
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - type: bind
        source: ./config/registry/appsettings.Production.json
        target: /app/appsettings.Production.json
      - type: bind
        source: ./config/registry/keys
        target: /keys
    restart: on-failure
    networks:
      - iam4cc
  openfga:
    image: openfga/openfga
    ports:
      - "6005:8080" # HTTP Server
      #- "6006:8081" # gRPC API
      #- "3000:3000" # Playground
    environment:
      - ASPNETCORE_HTTP_PORTS=6002
    command: run
    restart: on-failure
    networks:
      - iam4cc
networks:
  iam4cc:
volumes:
  auth-sqlite:
